version: '3'
services:
  boltcard:
    image: chloej1100/boltcard:v1
    container_name: boltcard_main
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - LOG_LEVEL=DEBUG
      - DB_HOST=db
      - DB_USER=cardapp
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432    
      - DB_NAME=card_db
    expose: 
      - "9000"
      - "9001"
    volumes:
      - boltcard_files:/boltcard
    networks:
      - boltnet
  db:
    image: postgres
    container_name: boltcard_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=cardapp
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=card_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./select_db.sql:/docker-entrypoint-initdb.d/select_db.sql
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./settings.sql:/docker-entrypoint-initdb.d/settings.sql
    expose:
      - "5432"
    networks:
      - boltnet
  webserver:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - boltnet
  frontend:
    image: chloej1100/boltcard-gui:v1
    container_name: boltcard_frontend
    depends_on:
      - db
    environment:
      - DOCUMENT_ROOT=/var/www/html
      - SS_TRUSTED_PROXY_IPS=*
      - SS_ENVIRONMENT_TYPE=${SS_ENVIRONMENT_TYPE}
      - SS_DATABASE_SERVER=db
      - SS_DATABASE_NAME=card_db
      - SS_DATABASE_USERNAME=cardapp
      - SS_DATABASE_PASSWORD=${DB_PASSWORD}
      - SS_DEFAULT_ADMIN_USERNAME=${SS_DEFAULT_ADMIN_USERNAME}
      - SS_DEFAULT_ADMIN_PASSWORD=${SS_DEFAULT_ADMIN_PASSWORD}
      - SS_DATABASE_CLASS=PostgreSQLDatabase
    volumes:
      - boltcard_files:/boltcard-files
      - frontend_assets:/var/www/html/public/assets
      - frontend_resources:/var/www/html/public/_resources
      - frontend_graphql:/var/www/html/public/_graphql
      - frontend_graphql-generated:/var/www/html/.graphql-generated
      - frontend_vendor:/var/www/html/vendor
    expose:
      - "8080"
    networks:
      - boltnet
networks:
  boltnet:
volumes:
  db-data:
  caddy_data:
    external: true
  caddy_config:
  caddy_website:
  boltcard_files:
  frontend_assets:
  frontend_resources:
  frontend_graphql:
  frontend_graphql-generated:
  frontend_vendor: